####################################################
#
# Welcome to Tokyo Jekyll Theme
# Author Link : https://themeix.com/
# Version : v1.0.0
#
####################################################

# Site settings
title: "Jayson Valentino"
email: "jaysonvalentino22@gmail.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jayson-valentino.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/header-brand.png
description: "Software Engineer"
top_letest_news: true
keywords: "Software Engineer, DevOps, Cloud"
mailchimp: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884"
facebook: https://facebook.com/themeix
instagram: https://instagram.com/themeix
twitter: https://twitter.com/themeix_com
pinterest: https://pinterest.com/themeix

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  authors:
    output: true
    permalink: /author/:path/

feed:
  collections:
    posts:
      path: "/index.xml"
